server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: 'localhost:9092'
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    circuitbreaker:
      resilience4j:
        blocking:
          enable: true

management:
  endpoints.web.exposure.include: '*' # health,info,prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"

app:
  mongo:
    uri: "mongodb://localhost:27017"
    database: "users"
  clients:
    task-service:
      url: "http://localhost:8080"
