[tool.poetry]
name = "user-service"
version = "0.1.0"
description = "User service with Flask and OpenTelemetry"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.0"
opentelemetry-api = "^1.20.0"
opentelemetry-sdk = "^1.20.0"
opentelemetry-exporter-otlp = "^1.20.0"
opentelemetry-instrumentation-flask = "^0.41b0"
opentelemetry-instrumentation-requests = "^0.41b0"
opentelemetry-instrumentation-pymongo = "^0.41b0"
opentelemetry-exporter-zipkin = "^1.37.0"
flask-pymongo = "^2.3.0"
python-dotenv = "^1.0.0"
setuptools = "<81"
confluent-kafka = "2.1.1"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"